server:
  port: 4000


spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  main:
    allow-bean-definition-overriding: true

  application:
    name: backend

  mail:
    host: ${MAILER_HOST}
    port: ${MAILER_PORT}
    username: ${MAILER_USERNAME}
    password: ${MAILER_PASSWORD}
    admin_mail: ${MAILER_ADMIN_MAIL}
    admin_personal: ${MAILER_ADMIN_PERSONAL}
    mail_subject: ${MAILER_SUBJECT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  r2dbc:
    url: r2dbc:mariadb://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50


  sql:
    init:
      mode: always
      platform: mariadb
      schema-locations: classpath:schema.sql


springdoc:
  swagger-ui:
    path: /


payments:
  stripe:
    secret_key: ${PAYMENTS_STRIPE_SECRET_KEY}
    webhook_secret_key: ${PAYMENTS_STRIPE_WEBHOOK_SECRET_KEY}


cors:
  api_key: ${API_KEY}
  allowed_origins:
    - http://localhost:3000


cloudflare:
  account_id: ${CLOUDFLARE_ACCOUNT_ID}
  r2:
    access_key: ${CLOUDFLARE_R2_ACCESS_ID}
    secret_key: ${CLOUDFLARE_R2_SECRET_ID}
    bucket: ${CLOUDFLARE_R2_BUCKET}
    link_days_valid: ${CLOUDFLARE_R2_LINK_DAYS_VALID}
    file_name: ${CLOUDFLARE_R2_FILE_NAME}